name: HawkEye
main: uk.co.oliwali.HawkEye.HawkEye
authors: [oliverw92, GoalieGuy6]
version: ${project.version}
description: Track those griefers like a bird of prey!
softdepend: [WorldEdit,PermissionsEx,Permissions,GroupManager,bPermissions,Vault]
commands:
  hawk:
    description: Track those griefers like a bird of prey!
    aliases: [hawkeye,he,hk,ha]
    usage: /<command> help
permissions:
    hawkeye.*:
        description: Gives access to all HawkEye commands
        default: false
        children:
            hawkeye.search: true
            hawkeye.tpto: true
            hawkeye.rollback: true
            hawkeye.tool: true
            hawkeye.tool.bind: true
            hawkeye.notify: true
            hawkeye.preview: true
            hawkeye.page: true
            hawkeye.rebuild: true
    hawkeye.tool.*:
        description: Permission to use the HawkEye tool
        default: false
        children:
            hawkeye.tool.bind: true
